// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZJFrrF5nWkRui5LWRl-LP04MD8uQ3l4',
    appId: '1:52510703994:android:197efa919d3a5c110156c3',
    messagingSenderId: '52510703994',
    projectId: 'signbridge-6bc26',
    storageBucket: 'signbridge-6bc26.firebasestorage.app',
  );
}
